
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('posts').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('posts').insert({
          id: 1,
          title: 'Buddha Bowls',
          headline: 'These are great for post hike treats!',
          date: '1475441736566',
          category: 1,
          body: '<p>Buddha bowl=the largest bowl you have+the most delicious veggies in your kitchen (bonus points if they’re roasted)+some protein+as many sauces as you have tucked away in the door of your fridge. Fall Buddha Bowl= baked sweet potatoes+colorful roasted potato wedges+sautéed leafy dark greens+crispy chickpeas+the creamiest of sauces+basil confetti. Buddha bowls are the new salads/dinners/lunches and here’s why: they’re everything you could ever want in a salad/dinner/lunch. Because they’re versatile, they’re the perfect canvas for leftovers, and they require all the sauces.</p><p>Life has been really tough lately. I’m living in beautiful Colorado (I know, you feel really sorry for me), but I miss my family/dogs/desert sunsets and the general content that comes with knowing that you’re home. If the past six months have taught me anything, it’s that home is not just a structure with four walls and a roof that keeps you warm in the winter and cool in the summer. Home is the place my puppies are snoring on the couch, the place I feel like a contributing member of my community, and the place that makes me swell with pride every time I think about it. And I haven’t had a place to call home in six months.</p><p>I’ve always been able to find a little bit of home in the kitchen. The smell of onions and garlic bubbling on the stove will always remind me of the comfort of my Nanny’s house, and freshly baked banana bread never fails to bring me back to my mom’s kitchen. And so in this time of yearning I find myself in the kitchen more than ever, if only to awaken these fond memories of home.</p><p>Making (and subsequently eating) this buddha bowl was so therapeutic. Maybe it was all the carbs, or the creamy sauces, or the smell of herbs and garlic that rose from the oven. Maybe it was the tender sweet potato, the slightly crispy purple potatoes, or all of the vitamins in those leafy dark greens. Maybe it’s all of that comfort that puts the buddha in buddha bowl.</p>',
          ingredients: "'1 large sweet potato, cut in half lengthwise', '10 baby potatoes, cut into wedges','1 can chickpeas, rinsed and dried','1 bunch dark leafy greens (I used broccoli greens), roughly chopped','1 clove garlic, minced','2 tablespoons olive oil, divided','1 teaspoon sea salt, divided','freshly ground pepper','¼ cup fresh basil, chopped','For the tahini sauce:','¼ cup tahini','2 cloves garlic, pressed','2 tablespoons lemon juice','3 tablespoons water','½ teaspoon finely ground sea salt','¼ teaspoon freshly ground pepper','For the Parsley Sauce:','¼ cup olive oil','¼ cup fresh lemon juice','½ cup fresh flat leaf parsley','1 jalapeño, halved and seeded','2 tablespoons tahini','1.5 teaspoons ground cumin','1 teaspoon maple syrup','1 clove garlic, peeled','¼ teaspoon sea salt'"
        }),
        knex('posts').insert({
          id: 2,
          title: 'My Favorite Acai Bowl',
          headline: 'WARNING: This will make your mouth red!',
          date: '1475421736566',
          category: 3,
          body: '<p>WARNING: My favorite acai bowl WILL turn your lips red. But, it’s a pretty shade of red and tastes considerably better than lipstick, so you really don’t have anything to worry about.</p><p>My acai bowl awakening came in the summer of 2013, when I took a trip to Maui, Hawaii. I loved snorkeling with sea turtles and watching purple-y orange sunsets, but I will never forget the raw vegan cafe, Choice, that I ate at almost every day. Before this trip, I thought that a raw vegan diet consisted of a bunch of carrots and cucumbers. Which are great, but…boring. Choice completely blew my mind. I ate raw vegan ravioli, raw vegan brownies, and raw vegan pizza. And then, on a beautiful warm morning, I tried one of the acai bowls at Choice. A mountainous, thick, deep purple smoothie was served in a bowl. A smoothie in a bowl! Topped with sliced strawberries, bananas, goji berries, shredded coconut, cacao nibs, and bee pollen, it remains the most glorious thing I have ever seen. And I’ve been to the Grand Canyon.</p><p>Needless to say, I was in deep withdrawal when I returned home to Arizona at the end of the trip. I scoured every smoothie shop around, but never found an acai bowl that compared to the one at Choice. So, I returned to the kitchen to create my own. I had some failures (I do not recommend putting dried figs on your acai bowl). But eventually, with the discovery of Sambazon Acai juice, I was able to create an incredible acai bowl at home.</p><p>This acai bowl isn’t just a weak substitute for the good stuff. It is the good stuff. It’s a rich, creamy smoothie bowl filled with frozen fruit, chia seeds, greens, and acai juice. It’s toppings such as sliced bananas, berries, nuts, coconut, and chocolate, but not dried figs. It’s breakfast. It’s lunch. It’s dessert. And best of all, it’s not ten dollars.</p>',
          ingredients: "'⅓ cup frozen mango pieces','1 cup frozen peach slices','½ cup frozen blueberries','½ ripe banana','½ cup kale or spinach (optional)','1 tablespoon chia seeds','¼ cup original acai juice, such as Sambazon','Optional Toppings:','sliced bananas','berries','shredded coconut','cacao nibs','bee pollen','raw honey','goji berries','nuts'"
        })
      ]);
    });
};
