
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('posts').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('posts').insert({
          id: 1,
          title: 'Buddha Bowls',
          headline: 'These are great for post hike treats!',
          date: '1474321736566',
          category_id: 1,
          body: '<p>Buddha bowl=the largest bowl you have+the most delicious veggies in your kitchen (bonus points if they’re roasted)+some protein+as many sauces as you have tucked away in the door of your fridge. Fall Buddha Bowl= baked sweet potatoes+colorful roasted potato wedges+sautéed leafy dark greens+crispy chickpeas+the creamiest of sauces+basil confetti. Buddha bowls are the new salads/dinners/lunches and here’s why: they’re everything you could ever want in a salad/dinner/lunch. Because they’re versatile, they’re the perfect canvas for leftovers, and they require all the sauces.</p><p>Life has been really tough lately. I’m living in beautiful Colorado (I know, you feel really sorry for me), but I miss my family/dogs/desert sunsets and the general content that comes with knowing that you’re home. If the past six months have taught me anything, it’s that home is not just a structure with four walls and a roof that keeps you warm in the winter and cool in the summer. Home is the place my puppies are snoring on the couch, the place I feel like a contributing member of my community, and the place that makes me swell with pride every time I think about it. And I haven’t had a place to call home in six months.</p><p>I’ve always been able to find a little bit of home in the kitchen. The smell of onions and garlic bubbling on the stove will always remind me of the comfort of my Nanny’s house, and freshly baked banana bread never fails to bring me back to my mom’s kitchen. And so in this time of yearning I find myself in the kitchen more than ever, if only to awaken these fond memories of home.</p><p>Making (and subsequently eating) this buddha bowl was so therapeutic. Maybe it was all the carbs, or the creamy sauces, or the smell of herbs and garlic that rose from the oven. Maybe it was the tender sweet potato, the slightly crispy purple potatoes, or all of the vitamins in those leafy dark greens. Maybe it’s all of that comfort that puts the buddha in buddha bowl.</p>',
          ingredients: "<ul><li>1 large sweet potato, cut in half lengthwise</li><li>10 baby potatoes, cut into wedges</li><li>1 can chickpeas, rinsed and dried</li><li>1 bunch dark leafy greens (I used broccoli greens), roughly chopped</li><li>1 clove garlic, minced</li><li>2 tablespoons olive oil, divided</li><li>1 teaspoon sea salt, divided</li><li>freshly ground pepper</li><li>¼ cup fresh basil, chopped</li><li>For the tahini sauce:</li><li>¼ cup tahini</li><li>2 cloves garlic, pressed</li><li>2 tablespoons lemon juice</li><li>3 tablespoons water</li><li>½ teaspoon finely ground sea salt</li><li>¼ teaspoon freshly ground pepper</li><li>For the Parsley Sauce:</li><li>¼ cup olive oil</li><li>¼ cup fresh lemon juice</li><li>½ cup fresh flat leaf parsley</li><li>1 jalapeño, halved and seeded</li><li>2 tablespoons tahini</li><li>1.5 teaspoons ground cumin</li><li>1 teaspoon maple syrup</li><li>1 clove garlic, peeled</li><li>¼ teaspoon sea salt</li></ul>",
          instructions: "<ol><li>Heat the oven to 400 degrees.</li><li>Place both haves of the sweet potato and all of the potato wedges on a baking tray.</li><li>Drizzle one tablespoon of olive oil, ½ teaspoon sea salt, and freshly ground pepper on the potatoes. Toss to combine.</li><li>Place the chickpeas on a second baking tray. Drizzle ½ tablespoon olive oil, ¼ teaspoon sea salt, and freshly ground pepper over the chickpeas. Toss to combine.</li><li>Roast the potatoes and chickpeas in the same oven for 17 minutes. Remove the chickpeas from the oven.</li><li>Toss the potato wedges. Continue cooking the potato wedges and sweet potato halves for another 15-20 minutes, or until wedges are slightly crispy and sweet potatoes are tender. Remove from the oven.</li><li>While the potatoes and chickpeas are roasting, heat remaining ½ tablespoon olive oil in a small skillet over low-medium heat. Add the minced garlic and sauté for 30 seconds. Add the leafy greens, ¼ teaspoon sea salt, and freshly ground pepper. Cook for 1-2 minutes, or until the greens are slightly wilted. Remove from the heat.</li><li>Once the greens have been cooked, make the sauces.</li><li>To make the tahini sauce, Add tahini, garlic cloves, lemon juice, water, sea salt, and pepper to a bowl. Whisk vigorously until all ingredients are combined and the sauce is smooth and creamy.</li><li>To make the parsley sauce:</li><li>Add olive oil, lemon juice, parsley, jalapeño, tahini, cumin, maple syrup, garlic clove, and sea salt to a blender. Blend the ingredients for about one minute, or until the ingredients are well combined.</li><li>Dice the sweet potato halves into one inch cubes. Divide the diced sweet potatoes, potato wedges, leafy greens, and chickpeas into two bowls. Drizzle each bowl with as much tahini and parsley sauce as you want. Sprinkle each bowl with freshly chopped basil.</li></ol>"
        }),
        knex('posts').insert({
          id: 2,
          title: 'My Favorite Acai Bowl',
          headline: 'WARNING: This will make your mouth red!',
          date: '1473311736566',
          category_id: 3,
          body: '<p>WARNING: My favorite acai bowl WILL turn your lips red. But, it’s a pretty shade of red and tastes considerably better than lipstick, so you really don’t have anything to worry about.</p><p>My acai bowl awakening came in the summer of 2013, when I took a trip to Maui, Hawaii. I loved snorkeling with sea turtles and watching purple-y orange sunsets, but I will never forget the raw vegan cafe, Choice, that I ate at almost every day. Before this trip, I thought that a raw vegan diet consisted of a bunch of carrots and cucumbers. Which are great, but…boring. Choice completely blew my mind. I ate raw vegan ravioli, raw vegan brownies, and raw vegan pizza. And then, on a beautiful warm morning, I tried one of the acai bowls at Choice. A mountainous, thick, deep purple smoothie was served in a bowl. A smoothie in a bowl! Topped with sliced strawberries, bananas, goji berries, shredded coconut, cacao nibs, and bee pollen, it remains the most glorious thing I have ever seen. And I’ve been to the Grand Canyon.</p><p>Needless to say, I was in deep withdrawal when I returned home to Arizona at the end of the trip. I scoured every smoothie shop around, but never found an acai bowl that compared to the one at Choice. So, I returned to the kitchen to create my own. I had some failures (I do not recommend putting dried figs on your acai bowl). But eventually, with the discovery of Sambazon Acai juice, I was able to create an incredible acai bowl at home.</p><p>This acai bowl isn’t just a weak substitute for the good stuff. It is the good stuff. It’s a rich, creamy smoothie bowl filled with frozen fruit, chia seeds, greens, and acai juice. It’s toppings such as sliced bananas, berries, nuts, coconut, and chocolate, but not dried figs. It’s breakfast. It’s lunch. It’s dessert. And best of all, it’s not ten dollars.</p>',
          ingredients: "<ul><li>⅓ cup frozen mango pieces</li><li>1 cup frozen peach slices</li><li>½ cup frozen blueberries</li><li>½ ripe banana</li><li>½ cup kale or spinach (optional)</li><li>1 tablespoon chia seeds</li><li>¼ cup original acai juice, such as Sambazon</li><li>Optional Toppings:</li><li>sliced bananas</li><li>berries</li><li>shredded coconut</li><li>cacao nibs</li><li>bee pollen</li><li>raw honey</li><li>goji berries</li><li>nuts</li></ul>",
          instructions: "<ol><li>Place mangoes, peaches, blueberries, banana, greens, chia seeds, and acai juice in a high speed blender or food processor.</li><li>Blend the ingredients until they create a thick and creamy smoothie.</li><li>Spoon the smoothie into a bowl.</li><li>Top the smoothie with your toppings of choice.</li></ol>"
        }),
        knex('posts').insert({
          id: 3,
          title: 'Peachy Keen Cheesecake',
          headline: 'It\'s just peachy!',
          date: '1472000736566',
          category_id: 3,
          body: '<p>This was supposed to be a vegan caramel cheesecake. Things with the vegan caramel cheesecake took a turn for the worse when I burnt the vegan caramel and made the house smell so bad that I had to burn three sticks of incense to make it bearable to be inside. So. When you can’t figure out vegan caramel cheesecake, it’s Peachy Keen Cheesecake to the rescue. Because local in-season peaches make everything okay.</p><p>You’ve had local in-season peaches, right? They’re soft, and juicy, and slightly tart, and they fall right off the pit. They basically beg you to eat them, calling out to you from their heaping fruit bowl on the kitchen counter. I dare you to resist their call.</p><p>You can’t go wrong eating seasonal peaches as they are. You can’t go wrong smothering them with a scoop of sweet, creamy, vanilla ice cream. You especially can’t go wrong simmering them into a sweet, thick preserve and swirling them through a cashew-based vegan cheesecake.</p><p>Yup, vegan cashew-based cheesecake. With a date-oat-walnut crust and a creamy, non-dairy filling. Without any processed sugars or need for baking. Isn’t life sweet?</p><p>A house that smells like burnt caramel isn’t so bad when the result is a Peachy Keen Cheesecake.</p>',
          ingredients: '<ul><li>3 peaches, chopped into ½" pieces</li><li>¼ cup water</li><li>1 T maple syrup, honey, or brown rice syrup</li><li>1 cup oats, toasted</li><li>½ cup walnuts, toasted</li><li>¼ teaspoon sea salt</li><li>½ teaspoon pumpkin pie spice</li><li>1.25 cups pitted Medjool dates</li><li>1.5 cups raw soaked cashews</li><li>2 T fresh lemon juice</li><li>1 teaspoon vanilla extract</li><li>¼ cup coconut oil, melted</li><li>½ cup full fat coconut milk</li><li>⅓ cup brown rice syrup or maple syrup</li></ul>',
          instructions: '<ol><li>Place cashews in a medium-sized bowl. Pour three cups of boiling water over the cashews and allow them to soak for an hour.</li><li>Combine chopped peaches, water, and maple syrup in a small saucepan over medium-low heat. Allow the mixture to simmer for 15-20 minutes until the mixture has thickened. Remove from heat and allow to cool.</li><li>Place oats, walnuts, sea salt, pumpkin pie spice, and Medjool dates in a food processor. Pulse the ingredients together until they are fine. Press the mixture into the bottom of a 9-inch cake pan or spring form pan.</li><li>Drain the cashews and add them to a high-speed blender with the lemon juice, vanilla, coconut oil, coconut milk, and brown rice syrup. Blend the mixture until it is smooth and creamy. Pour the mixture into the cake pan over the prepared crust.</li><li>Spoon the cooked peaches over the cheesecake filling. Use a knife to gently swirl the peaches through the filling.</li><li>Freeze the cheesecake for at least 4 hours. Remove the cheesecake from the freezer 20 minutes before serving.</li><li>Store in the freezer.</li></ol>'
        })
        knex('posts').insert({
          id: 4,
          title: 'Banana Bread Granola',
          headline: 'Get some.',
          date: '1472000735366',
          category_id: 4,
          body: '<p> </p>',
          ingredients: '<ul><li> </li></ul>',
          instructions: '<ol><li> </li></ol>'
        })
      ]);
    });
};
